name: ui_exp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.6

dependencies:
  bezier: ^1.2.0
  dotted_border: ^2.0.0+3
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  intl: ^0.18.0
  vector_math: ^2.1.4
  flutter_shaders: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  shaders:
    - shaders/ripple.frag
    - shaders/simple.frag
